// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/Mldlr/storety/internal/server/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

type Storage_Expecter struct {
	mock *mock.Mock
}

func (_m *Storage) EXPECT() *Storage_Expecter {
	return &Storage_Expecter{mock: &_m.Mock}
}

// CreateData provides a mock function with given fields: ctx, data
func (_m *Storage) CreateData(ctx context.Context, data *models.Data) error {
	ret := _m.Called(ctx, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Data) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_CreateData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateData'
type Storage_CreateData_Call struct {
	*mock.Call
}

// CreateData is a helper method to define mock.On call
//   - ctx context.Context
//   - data *models.Data
func (_e *Storage_Expecter) CreateData(ctx interface{}, data interface{}) *Storage_CreateData_Call {
	return &Storage_CreateData_Call{Call: _e.mock.On("CreateData", ctx, data)}
}

func (_c *Storage_CreateData_Call) Run(run func(ctx context.Context, data *models.Data)) *Storage_CreateData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Data))
	})
	return _c
}

func (_c *Storage_CreateData_Call) Return(_a0 error) *Storage_CreateData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_CreateData_Call) RunAndReturn(run func(context.Context, *models.Data) error) *Storage_CreateData_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSession provides a mock function with given fields: ctx, session, oldSession
func (_m *Storage) CreateSession(ctx context.Context, session *models.Session, oldSession *models.Session) error {
	ret := _m.Called(ctx, session, oldSession)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Session, *models.Session) error); ok {
		r0 = rf(ctx, session, oldSession)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type Storage_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - session *models.Session
//   - oldSession *models.Session
func (_e *Storage_Expecter) CreateSession(ctx interface{}, session interface{}, oldSession interface{}) *Storage_CreateSession_Call {
	return &Storage_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, session, oldSession)}
}

func (_c *Storage_CreateSession_Call) Run(run func(ctx context.Context, session *models.Session, oldSession *models.Session)) *Storage_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Session), args[2].(*models.Session))
	})
	return _c
}

func (_c *Storage_CreateSession_Call) Return(_a0 error) *Storage_CreateSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_CreateSession_Call) RunAndReturn(run func(context.Context, *models.Session, *models.Session) error) *Storage_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, user
func (_m *Storage) CreateUser(ctx context.Context, user *models.User) error {
	ret := _m.Called(ctx, user)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type Storage_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.User
func (_e *Storage_Expecter) CreateUser(ctx interface{}, user interface{}) *Storage_CreateUser_Call {
	return &Storage_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *Storage_CreateUser_Call) Run(run func(ctx context.Context, user *models.User)) *Storage_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.User))
	})
	return _c
}

func (_c *Storage_CreateUser_Call) Return(_a0 error) *Storage_CreateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_CreateUser_Call) RunAndReturn(run func(context.Context, *models.User) error) *Storage_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDataByName provides a mock function with given fields: ctx, userID, name
func (_m *Storage) DeleteDataByName(ctx context.Context, userID uuid.UUID, name string) error {
	ret := _m.Called(ctx, userID, name)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, userID, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_DeleteDataByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDataByName'
type Storage_DeleteDataByName_Call struct {
	*mock.Call
}

// DeleteDataByName is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - name string
func (_e *Storage_Expecter) DeleteDataByName(ctx interface{}, userID interface{}, name interface{}) *Storage_DeleteDataByName_Call {
	return &Storage_DeleteDataByName_Call{Call: _e.mock.On("DeleteDataByName", ctx, userID, name)}
}

func (_c *Storage_DeleteDataByName_Call) Run(run func(ctx context.Context, userID uuid.UUID, name string)) *Storage_DeleteDataByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *Storage_DeleteDataByName_Call) Return(_a0 error) *Storage_DeleteDataByName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_DeleteDataByName_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *Storage_DeleteDataByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllDataInfo provides a mock function with given fields: ctx, userID
func (_m *Storage) GetAllDataInfo(ctx context.Context, userID uuid.UUID) ([]models.DataInfo, error) {
	ret := _m.Called(ctx, userID)

	var r0 []models.DataInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.DataInfo, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.DataInfo); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.DataInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_GetAllDataInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllDataInfo'
type Storage_GetAllDataInfo_Call struct {
	*mock.Call
}

// GetAllDataInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *Storage_Expecter) GetAllDataInfo(ctx interface{}, userID interface{}) *Storage_GetAllDataInfo_Call {
	return &Storage_GetAllDataInfo_Call{Call: _e.mock.On("GetAllDataInfo", ctx, userID)}
}

func (_c *Storage_GetAllDataInfo_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *Storage_GetAllDataInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *Storage_GetAllDataInfo_Call) Return(_a0 []models.DataInfo, _a1 error) *Storage_GetAllDataInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_GetAllDataInfo_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.DataInfo, error)) *Storage_GetAllDataInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetDataContentByName provides a mock function with given fields: ctx, userID, name
func (_m *Storage) GetDataContentByName(ctx context.Context, userID uuid.UUID, name string) ([]byte, string, error) {
	ret := _m.Called(ctx, userID, name)

	var r0 []byte
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) ([]byte, string, error)); ok {
		return rf(ctx, userID, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) []byte); ok {
		r0 = rf(ctx, userID, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) string); ok {
		r1 = rf(ctx, userID, name)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, string) error); ok {
		r2 = rf(ctx, userID, name)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Storage_GetDataContentByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDataContentByName'
type Storage_GetDataContentByName_Call struct {
	*mock.Call
}

// GetDataContentByName is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - name string
func (_e *Storage_Expecter) GetDataContentByName(ctx interface{}, userID interface{}, name interface{}) *Storage_GetDataContentByName_Call {
	return &Storage_GetDataContentByName_Call{Call: _e.mock.On("GetDataContentByName", ctx, userID, name)}
}

func (_c *Storage_GetDataContentByName_Call) Run(run func(ctx context.Context, userID uuid.UUID, name string)) *Storage_GetDataContentByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *Storage_GetDataContentByName_Call) Return(_a0 []byte, _a1 string, _a2 error) *Storage_GetDataContentByName_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Storage_GetDataContentByName_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) ([]byte, string, error)) *Storage_GetDataContentByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetIdPassByName provides a mock function with given fields: ctx, username
func (_m *Storage) GetIdPassByName(ctx context.Context, username string) (uuid.UUID, string, error) {
	ret := _m.Called(ctx, username)

	var r0 uuid.UUID
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (uuid.UUID, string, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) uuid.UUID); ok {
		r0 = rf(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, username)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Storage_GetIdPassByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIdPassByName'
type Storage_GetIdPassByName_Call struct {
	*mock.Call
}

// GetIdPassByName is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *Storage_Expecter) GetIdPassByName(ctx interface{}, username interface{}) *Storage_GetIdPassByName_Call {
	return &Storage_GetIdPassByName_Call{Call: _e.mock.On("GetIdPassByName", ctx, username)}
}

func (_c *Storage_GetIdPassByName_Call) Run(run func(ctx context.Context, username string)) *Storage_GetIdPassByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Storage_GetIdPassByName_Call) Return(_a0 uuid.UUID, _a1 string, _a2 error) *Storage_GetIdPassByName_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Storage_GetIdPassByName_Call) RunAndReturn(run func(context.Context, string) (uuid.UUID, string, error)) *Storage_GetIdPassByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function with given fields: ctx, sessionID, refreshToken
func (_m *Storage) GetSession(ctx context.Context, sessionID uuid.UUID, refreshToken string) (uuid.UUID, error) {
	ret := _m.Called(ctx, sessionID, refreshToken)

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (uuid.UUID, error)); ok {
		return rf(ctx, sessionID, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) uuid.UUID); ok {
		r0 = rf(ctx, sessionID, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, sessionID, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type Storage_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
//   - refreshToken string
func (_e *Storage_Expecter) GetSession(ctx interface{}, sessionID interface{}, refreshToken interface{}) *Storage_GetSession_Call {
	return &Storage_GetSession_Call{Call: _e.mock.On("GetSession", ctx, sessionID, refreshToken)}
}

func (_c *Storage_GetSession_Call) Run(run func(ctx context.Context, sessionID uuid.UUID, refreshToken string)) *Storage_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *Storage_GetSession_Call) Return(_a0 uuid.UUID, _a1 error) *Storage_GetSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_GetSession_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (uuid.UUID, error)) *Storage_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewStorage interface {
	mock.TestingT
	Cleanup(func())
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStorage(t mockConstructorTestingTNewStorage) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
